### ISSUE TITLE
一部のタスクが壁裏からできてしまう

### ISSUE THREAD

**Issue by Maximilian2022** [tomarai/AUShipMod#1]
作成者様
いつもありがとうございます。

エレクトリカルのバー上げタスク後にカチっとするだけのタスクが武器庫またはメインホールで沸いた場合に壁裏からできてしまいます
可能であればこちらもご対応いただけますと幸いです。

よろしくお願いいたします

**Comment by tomarai** [comment]
ありがとうございます
こちら試してみてください
https://github.com/tomarai/AUShipMod/releases/tag/v0.0.3-alpha

**Comment by Maximilian2022** [comment]
tomarai様
対応ありがとうございます！

確認させていただきました！
個人的には大満足です。ご対応誠にありがとうございました！
